name: POI CICD

on:
  push:
    branches: [ main ]
    paths:
      - apis/poi/poi.sln/**
      - .github/workflows/poi-cicd.yml
  pull_request:
    branches: [ main ]
    paths:
      - apis/poi/poi.sln/**
      - .github/workflows/poi-cicd.yml

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.202

    - name: Add Code Coverage Tools
      working-directory: apis/poi/tests/UnitTests
      run: dotnet add package coverlet.msbuild
    
    - name: Restore dependencies
      run: dotnet restore apis/poi/web/*.csproj
    
    - name: Build Web
      run: dotnet build --configuration Release --no-restore apis/poi/web/*.csproj
    
    - name: Build Unit Tests
      run: dotnet build --configuration Release apis/poi/tests/UnitTests/UnitTests.csproj
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal apis/poi/tests/UnitTests /p:CollectCoverage=true /p:CoverletOutput=lcov/ /p:CoverletOutputFormat=lcov
      
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: apis/poi/tests/UnitTests/lcov/coverage.info
        base-path: apis/poi
        flag-name: Unit
